name: Check PHP syntax errors
uses: overtrue/phplint@2.0.2
  with:
    # path to check
    path: # optional, default is .
    # command options.(eg: --no-cache --exclude=*.log)
    options: # optional, default is 
